[package]
name = "apples-to-apples"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
dsl-ractor = "0.2.1"
nom = "8.0.0"
ractor = "0.15.9"
tokio = { version = "1.48.0", features = ["full"] }
